#pragma once

void testPlayerTurnOrder();
void testPlayerScoreCompute();
void testPlayerPerformanceScore();

void TP_test_01();
void TP_test_02();
void TP_test_03();
void TP_test_04();
void TP_test_05();
void TP_test_06();
void TP_test_07();
void TP_test_08();
void TP_test_09();
void TP_test_10();
void TP_test_11();
void TP_test_12();
void TP_test_13();
void TP_test_14();
void TP_test_15();
void TP_test_16();
void TP_test_17();
void TP_test_18();
void TP_test_19();
void TP_test_20();
void TP_test_21();
void TP_test_22();
void TP_test_23();
void TP_test_24();
void TP_test_25();