#pragma once
#pragma once

// 25 test declarations for TestUtils
void TU_test_01();
void TU_test_02();
void TU_test_03();
void TU_test_04();
void TU_test_05();
void TU_test_06();
void TU_test_07();
void TU_test_08();
void TU_test_09();
void TU_test_10();
void TU_test_11();
void TU_test_12();
void TU_test_13();
void TU_test_14();
void TU_test_15();
void TU_test_16();
void TU_test_17();
void TU_test_18();
void TU_test_19();
void TU_test_20();
void TU_test_21();
void TU_test_22();
void TU_test_23();
void TU_test_24();
void TU_test_25();